#Intermediate Code which is generated by our parser from "cclang_script.txt" and this will run with the game engine.
import pygame
import vars
vars.NUM_COLS = 15
vars.NUM_ROWS = 15
import tetris_game as tt
from tetris_game import start_game
tt.HORIZON = 1
tt.FALL_SPEED =6
tt.GAME_MODE = 2
tt.J = 1
cus_arr = ["0110", "0110", "1111", "1111"]
tt.shapes.append(cus_arr)
tt.shape.append([cus_arr, tt.rotate(cus_arr), tt.rotate(tt.rotate(cus_arr)), tt.rotate(tt.rotate(tt.rotate(cus_arr)))])
start_game()
